# Generated by Django 5.0.6 on 2024-07-06 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="canceled",
        ),
        migrations.RemoveField(
            model_name="room",
            name="is_available",
        ),
    ]
