# Generated by Django 5.0.6 on 2024-07-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_booking_canceled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
