# Generated by Django 5.0.6 on 2024-07-02 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_alter_booking_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Total price",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="end_date",
            field=models.DateField(verbose_name="End date"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="rooms.room",
                verbose_name="Room",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="start_date",
            field=models.DateField(verbose_name="Start date"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="capacity",
            field=models.IntegerField(verbose_name="Capacity"),
        ),
        migrations.AlterField(
            model_name="room",
            name="is_available",
            field=models.BooleanField(default=True, verbose_name="Available now?"),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.PositiveSmallIntegerField(verbose_name="Room"),
        ),
        migrations.AlterField(
            model_name="room",
            name="price_per_day",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Price per day"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("standard", "Standard"),
                    ("deluxe", "Deluxe"),
                    ("suite", "Suite"),
                ],
                default="standard",
                max_length=10,
                verbose_name="Room Type",
            ),
        ),
    ]
